#!/bin/sh

set -e

#DEB

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/elasticsearch'
DIR_CONF='/etc/sds/connectors/elasticsearch'
DIR_CONF='/etc/sds/connectors/elasticsearch'
DIR_LOG='/var/log/sds/connectors/elasticsearch'


chmod 755 /etc/init.d/connector_elasticsearch
chmod 755 /opt/sds/connectors/elasticsearch/bin
chmod +x /opt/sds/connectors/elasticsearch/bin/stratio-connector-elasticsearch
chmod +x /etc/default/elasticsearch_connector
export ELASTICSEARCH_CONNECTOR_LIB=/opt/sds/connectors/elasticsearch
export ELASTICSEARCH_CONNECTOR_CONF="/etc/sds/connectors/elasticsearch"


case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
    mkdir $DIR_LOG
  fi

  chown root:root /etc/init.d/connector_elasticsearch
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod 775 $DIR_LOG

  sed -i 's!"$BASEDIR"/conf!/etc/sds/connectors/elasticsearch!g' /opt/sds/connectors/elasticsearch/bin/stratio-connector-elasticsearch

  update-rc.d connector_elasticsearch defaults
  ;;
esac    


exit 0

