#!/bin/sh

set -e

GROUP='stratio'
USER='stratio'
DIR_INSTALL='/opt/sds/connectors/elasticsearch'
DIR_CONF='/etc/sds/connectors/elasticsearch'
DIR_LOG='/var/log/sds/connectors/elasticsearch'

cp /opt/sds/stratio-connector-elasticsearch/template/ElasticSearchConnector /etc/init.d/stratio-connector-elasticsearch
chmod 755 /etc/init.d/stratio-connector-elasticsearch
chmod 755 /opt/sds/connectors/elasticsearch/bin
chmod +x /opt/sds/connectors/elasticsearch/bin/stratio-connector-elasticsearch
chmod +x /etc/default/stratio-connector-elasticsearch
export ELASTICSEARCH_CONNECTOR_LIB=/opt/sds/connectors/elasticsearch
export ELASTICSEARCH_CONNECTOR_CONF="/etc/sds/connectors/elasticsearch"

case "$1" in
  configure)

  # Add stratio group if it doesn't already exists
  if ! getent group $GROUP >/dev/null 2>&1; then
    groupadd ${GROUP} 
  fi

  # Add stratio user if it doesn't already exists
  if ! getent passwd $USER >/dev/null 2>&1; then
    [ -d /opt ] || mkdir /opt
    useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
  else
    usermod -G $GROUP $USER
  fi

  if [ ! -d "$DIR_LOG" ]; then
   echo "entra"
    mkdir $DIR_LOG
  fi
echo "SALE"

  chown -R ${USER}:${GROUP} /opt/sds /etc/sds

  chown root:root /etc/init.d/stratio-connector-elasticsearch
 
  chown -R ${USER}:${GROUP} $DIR_INSTALL
  ln -s $DIR_INSTALL/conf $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_CONF
  chown -R ${USER}:${GROUP} $DIR_LOG
  chmod -R 775 $DIR_INSTALL
  chmod 775 $DIR_LOG
  
  update-rc.d stratio-connector-elasticsearch defaults

  ;;
esac    


exit 0

